# ------------------------------
# hugo config
# ------------------------------

title = "astropenguin"
baseURL = "https://astropengu.in/"
defaultContentLanguage = "ja"
theme = "stack"
enableRobotsTXT = true
enableGitInfo = true
enableEmoji = true
paginate = 5

[author]
name = "Akio Taniguchi"
email = "taniguchi@a.phys.nagoya-u.ac.jp"
link = "https://astropengu.in"

[build]
noJSConfigInAssets = true

[languages.ja]
weight = 1
languageCode = "ja"
languageName = "Ja"
hasCJKLanguage = true
summaryLength = 100

[languages.en]
weight = 2
languageCode = "en"
languageName = "En"
hasCJKLanguage = false
summaryLength = 80

[markup.highlight]
style = "dracula"

[[menu.main]]
identifier = "home"
name = "Home"
url = "/"
pre = "home"
weight = 1

[[menu.main]]
identifier = "about"
name = "About"
url = "/about"
pre = "user"
weight = 2

[[menu.main]]
identifier = "search"
name = "Search"
url = "/search"
pre = "search"
weight = 3

[[menu.main]]
identifier = "github"
name = "GitHub"
url = "https://github.com/astropenguin/"
pre = "github"
weight = 10

[[menu.main]]
identifier = "twitter"
name = "Twitter"
url = "https://twitter.com/astropengu_in/"
pre = "twitter"
weight = 11

[[menu.main]]
identifier = "Papers"
name = "Papers"
url = "https://scholar.google.com/citations?user=O4aEvvcAAAAJ"
pre = "school"
weight = 12

[permalinks]
post = "/posts/:filename"
page = "/:filename"

# ------------------------------
# theme config
# ------------------------------

[params]
mainSections = ["post"]

[params.article.license]
enabled = true
default = "Licensed under CC BY 4.0"

[params.colorScheme]
toggle = true
default = "auto"

[params.comments]
enabled = false

[params.dateFormat]
published = "2006-01-02"
lastUpdated = "2006-01-02 15:04 MST"

[params.defaultImage.opengraph]
enabled = false

[params.footer]
since = 2018

[params.opengraph.twitter]
site = "astropengu_in"
card = "summary_large_image"

[params.sidebar]
subtitle = "Akio Taniguchi's website"

[params.sidebar.avatar]
src = "https://www.gravatar.com/avatar/631d6d325e5913f5e9ea9a500c761b0b?s=150"

[params.widgets]
enabled = ["search", "archives", "tag-cloud"]

[params.widgets.archives]
limit = 10
path = "archives"

[params.widgets.tagCloud]
limit = 30
